modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="http://github.com/hnOsmium0001/StevesTasks/issues"
displayURL="http://github.com/hnOsmium0001/StevesTasks/"
authors="hnOsmium0001"

[[mods]]
modId="stevestasks"
version="${file.jarVersion}"
displayName="Steve's Tasks"
description='''
Steve's Tasks
'''

[[dependencies.stevestasks]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.stevestasks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"

[[dependencies.stevestasks]]
    modId="sfm"
    mandatory=true
    versionRange="[3.0.0,)"
    ordering="NONE"
    side="BOTH"

