modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="http://github.com/hnOsmium0001/StevesTasks/issues"
displayURL="http://github.com/hnOsmium0001/StevesTasks"
authors="hnOsmium0001"

[[mods]]
modId="steves_tasks"
version="${file.jarVersion}"
displayName="Steve's Tasks"
description='''
Steve's Tasks
'''

[[dependencies.steves_tasks]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.steves_tasks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"

[[dependencies.steves_tasks]]
    modId="sfm"
    mandatory=true
    # TODO change for SFM release
    versionRange="[1.14.4-3.0.0-alpha,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.steves_tasks]]
    modId="refinedstorage"
    mandatory=false
    versionRange="[1.7,)"
    ordering="NONE"
    side="BOTH"
